apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-app
spec:
  selector:
    matchLabels:
      app: restaurant-app
  replicas: 2
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
      - name: restaurant-app
        image: samer955/myrestaurant:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
#  type: NodePort
  selector:
    app: restaurant-app
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  #  nodePort: 32323
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restaurant-ingress
spec:
  rules:
  - host: myrestaurant.info
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: restaurant-service
            port:
              number: 8080
