apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-app
spec:
  selector:
    matchLabels:
      app: restaurant-app
  replicas: 3
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
      - name: restaurant-app
        image: samer955/myrestaurant:latest
        ports:
        - containerPort: 8080
