apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  type: NodePort
  selector:
    app: restaurant-app
  ports:
  - port: 9898
    protocol: TCP
    targetPort: 8080
    nodePort: 32323